### ISSUE TITLE
the about section on the nav bar on yechiel.me is unclickable

### ISSUE THREAD

**Issue by JonDevOps** [achasveachas/yechiel-kalmenson-resume#2]

**Comment by achasveachas** [comment]
@jondevops it's only unclickable on the index page, because that's when the About links to. 

If you go to one of the other pages you'll notice that part of the navbar becomes unclickable while the About part becomes active (there's some slight coloring difference that's supposed to highlight the active status, I guess it's subtle enough that it can be missed)
